#!/usr/bin/env python3

# AP flight modes - DO NOT USE THESE, USE INTERNAL MODES!
# https://mavlink.io/en/messages/ardupilotmega.html#COPTER_MODE
COPTER_MODE_STABILIZE = 0
COPTER_MODE_GUIDED = 4     
COPTER_MODE_RTL = 6
COPTER_MODE_LAND = 9

# Internal modes, NOTE: Use these for performing mode switch
INTERNAL_MODE_STABILIZED = 100
INTERNAL_MODE_GUIDED_POS = 101
INTERNAL_MODE_GUIDED_VEL = 102
INTERNAL_MODE_RTL = 103
INTERNAL_MODE_LAND = 104


# Mapping internal → AP flight mode
INTERNAL_TO_COPTER_MODE = {
    INTERNAL_MODE_STABILIZED: COPTER_MODE_STABILIZE,
    INTERNAL_MODE_GUIDED_POS: COPTER_MODE_GUIDED,
    INTERNAL_MODE_GUIDED_VEL: COPTER_MODE_GUIDED,
    INTERNAL_MODE_RTL:        COPTER_MODE_RTL,
    INTERNAL_MODE_LAND:       COPTER_MODE_LAND,
}


# GeoPose command frame types:
FRAME_GLOBAL_INT = 5
FRAME_GLOBAL_REL_ALT = 6
FRAME_GLOBAL_TERRAIN_ALT = 11
